//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
using SQLite;
using System;

namespace WirelessConfigurationChanger.Database
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
        
         public void Create()
        {
            using (SQLiteConnection db = new SQLiteConnection(_path))
            {
                db.CreateTable<profile>();
            }
        }
    }
    public partial class profile
    {
        [PrimaryKey]
        [AutoIncrement]
        public Int32 id { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String name { get; set; }
        
        [MaxLength(50)]
        [NotNull]
        public String adapter_id { get; set; }
        
        [MaxLength(17)]
        [NotNull]
        public String bssid { get; set; }
        
        [MaxLength(32)]
        [NotNull]
        public String ssid { get; set; }
        
        [NotNull]
        public Byte dhcp_enabled { get; set; }
        
        [MaxLength(15)]
        public String ip_address { get; set; }
        
        [MaxLength(15)]
        public String subnet_mask { get; set; }
        
        [MaxLength(15)]
        public String gateway { get; set; }
        
        [NotNull]
        public Byte dns_auto { get; set; }
        
        [MaxLength(15)]
        public String preferred_dns_server { get; set; }
        
        [MaxLength(15)]
        public String alternate_dns_server { get; set; }
        
    }
    
}
